use_frameworks!
inhibit_all_warnings!

target 'MGMonthableDatePicker_Example' do
  pod 'MGMonthableDatePicker', :path => '../'

  target 'MGMonthableDatePicker_Tests' do
    inherit! :search_paths

    pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
